dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install tox tox-travis futures requests six pytest pytest-mock==1.10.4 pytest-cov coverage
script:
  - tox
